export const ID_MATCH_REGISTER_ORIGIN_REGULAR: number = 1

export const ID_MATCH_REGISTER_ORIGIN_HUNTING: number = 2

export const ID_MATCH_REGISTER_ORIGIN_PUBLIC_OFFER: number = 3

export const ID_MATCH_REGISTER_ORIGIN_CALCULATOR: number = 4

export const MATCH_REGISTER_ORIGIN_TYPES = {
	[ID_MATCH_REGISTER_ORIGIN_REGULAR]: 'regular',
	[ID_MATCH_REGISTER_ORIGIN_HUNTING]: 'hunting',
	[ID_MATCH_REGISTER_ORIGIN_PUBLIC_OFFER]: 'public_offer',
	[ID_MATCH_REGISTER_ORIGIN_CALCULATOR]: 'calculator',
}
